listen-address=172.20.22.15
listen-address=10.100.1.10
bind-interfaces
no-hosts
no-resolv
no-poll
domain-needed
bogus-priv
filter-AAAA
address=/spine1/10.250.255.11
address=/spine1/::
ptr-record=11.255.250.10.in-addr.arpa,spine1
address=/spine2/10.250.255.12
address=/spine2/::
ptr-record=12.255.250.10.in-addr.arpa,spine2
address=/leaf1/10.250.255.1
address=/leaf1/::
ptr-record=1.255.250.10.in-addr.arpa,leaf1
address=/leaf2/10.250.255.2
address=/leaf2/::
ptr-record=2.255.250.10.in-addr.arpa,leaf2
address=/leaf3/10.250.255.3
address=/leaf3/::
ptr-record=3.255.250.10.in-addr.arpa,leaf3
address=/gw-vlan100/10.100.1.1
address=/gw-vlan100/::
ptr-record=1.1.100.10.in-addr.arpa,gw-vlan100
address=/gw-vlan300/10.100.3.1
address=/gw-vlan300/::
ptr-record=1.3.100.10.in-addr.arpa,gw-vlan300
address=/host1/10.100.1.10
address=/host1/::
ptr-record=10.1.100.10.in-addr.arpa,host1
address=/host2/10.100.3.10
address=/host2/::
ptr-record=10.3.100.10.in-addr.arpa,host2
address=/host3/10.100.3.11
address=/host3/::
ptr-record=11.3.100.10.in-addr.arpa,host3
address=/leaf1-e1-1/10.250.1.0
address=/leaf1-e1-1/::
ptr-record=0.1.250.10.in-addr.arpa,leaf1-e1-1
address=/spine1-e1-1/10.250.1.1
address=/spine1-e1-1/::
ptr-record=1.1.250.10.in-addr.arpa,spine1-e1-1
address=/leaf1-e1-2/10.250.1.2
address=/leaf1-e1-2/::
ptr-record=2.1.250.10.in-addr.arpa,leaf1-e1-2
address=/spine2-e1-1/10.250.1.3
address=/spine2-e1-1/::
ptr-record=3.1.250.10.in-addr.arpa,spine2-e1-1
address=/leaf1-e1-4/10.250.11.0
address=/leaf1-e1-4/::
ptr-record=0.11.250.10.in-addr.arpa,leaf1-e1-4
address=/spine1-e1-5/10.250.11.1
address=/spine1-e1-5/::
ptr-record=1.11.250.10.in-addr.arpa,spine1-e1-5
address=/leaf1-e1-5/10.250.11.2
address=/leaf1-e1-5/::
ptr-record=2.11.250.10.in-addr.arpa,leaf1-e1-5
address=/spine2-e1-5/10.250.11.3
address=/spine2-e1-5/::
ptr-record=3.11.250.10.in-addr.arpa,spine2-e1-5
address=/leaf2-e1-1/10.250.2.0
address=/leaf2-e1-1/::
ptr-record=0.2.250.10.in-addr.arpa,leaf2-e1-1
address=/spine1-e1-2/10.250.2.1
address=/spine1-e1-2/::
ptr-record=1.2.250.10.in-addr.arpa,spine1-e1-2
address=/leaf2-e1-2/10.250.2.2
address=/leaf2-e1-2/::
ptr-record=2.2.250.10.in-addr.arpa,leaf2-e1-2
address=/spine2-e1-2/10.250.2.3
address=/spine2-e1-2/::
ptr-record=3.2.250.10.in-addr.arpa,spine2-e1-2
address=/leaf2-e1-3/10.250.12.0
address=/leaf2-e1-3/::
ptr-record=0.12.250.10.in-addr.arpa,leaf2-e1-3
address=/spine1-e1-6/10.250.12.1
address=/spine1-e1-6/::
ptr-record=1.12.250.10.in-addr.arpa,spine1-e1-6
address=/leaf2-e1-4/10.250.12.2
address=/leaf2-e1-4/::
ptr-record=2.12.250.10.in-addr.arpa,leaf2-e1-4
address=/spine2-e1-6/10.250.12.3
address=/spine2-e1-6/::
ptr-record=3.12.250.10.in-addr.arpa,spine2-e1-6
address=/leaf3-e1-1/10.250.3.0
address=/leaf3-e1-1/::
ptr-record=0.3.250.10.in-addr.arpa,leaf3-e1-1
address=/spine1-e1-3/10.250.3.1
address=/spine1-e1-3/::
ptr-record=1.3.250.10.in-addr.arpa,spine1-e1-3
address=/leaf3-e1-2/10.250.3.2
address=/leaf3-e1-2/::
ptr-record=2.3.250.10.in-addr.arpa,leaf3-e1-2
address=/spine2-e1-3/10.250.3.3
address=/spine2-e1-3/::
ptr-record=3.3.250.10.in-addr.arpa,spine2-e1-3
address=/leaf3-e1-5/10.250.13.0
address=/leaf3-e1-5/::
ptr-record=0.13.250.10.in-addr.arpa,leaf3-e1-5
address=/spine1-e1-7/10.250.13.1
address=/spine1-e1-7/::
ptr-record=1.13.250.10.in-addr.arpa,spine1-e1-7
address=/leaf3-e1-6/10.250.13.2
address=/leaf3-e1-6/::
ptr-record=2.13.250.10.in-addr.arpa,leaf3-e1-6
address=/spine2-e1-7/10.250.13.3
address=/spine2-e1-7/::
ptr-record=3.13.250.10.in-addr.arpa,spine2-e1-7
