{
 "title": "SR Linux Telemetry",
 "tags": [
  "srl-with-telemetry",
  "srl"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live Topology — bandwidth & link state",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(interface_oper_state, \"iface\", \"ethernet-$1/$2\", \"interface_name\", \"e(\\\\d+)-(\\\\d+)\")",
     "legendFormat": "oper-state:{{source}}:{{iface}}"
    },
    {
     "expr": "label_replace(interface_traffic_rate_out_bps, \"iface\", \"ethernet-$1/$2\", \"interface_name\", \"e(\\\\d+)-(\\\\d+)\")",
     "legendFormat": "{{source}}:{{iface}}:out"
    },
    {
     "expr": "label_replace(interface_traffic_rate_in_bps, \"iface\", \"ethernet-$1/$2\", \"interface_name\", \"e(\\\\d+)-(\\\\d+)\")",
     "legendFormat": "{{source}}:{{iface}}:in"
    }
   ]
  },
  { "title": "DC Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:IN"
    },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Active Routes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "Service: $Services",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "network_instance_oper_state{network_instance_name='$Services'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Router Front Panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "router_image - spine1",
     "type": "andrewbmchugh-flow-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "interface_oper_state{source=\"spine1\",interface_name=\"e1-1\"}",
       "legendFormat": "oper-state:spine1:ethernet-1/1"
      },
      {
       "expr": "interface_oper_state{source=\"spine1\",interface_name=\"e1-2\"}",
       "legendFormat": "oper-state:spine1:ethernet-1/2"
      },
      {
       "expr": "interface_oper_state{source=\"spine1\",interface_name=\"e1-3\"}",
       "legendFormat": "oper-state:spine1:ethernet-1/3"
      },
      {
       "expr": "interface_oper_state{source=\"spine1\",interface_name=\"e1-4\"}",
       "legendFormat": "oper-state:spine1:ethernet-1/4"
      },
      {
       "expr": "interface_oper_state{source=\"spine1\",interface_name=\"e1-5\"}",
       "legendFormat": "oper-state:spine1:ethernet-1/5"
      },
      {
       "expr": "interface_oper_state{source=\"spine1\",interface_name=\"e1-6\"}",
       "legendFormat": "oper-state:spine1:ethernet-1/6"
      }
     ]
    },
    {
     "title": "router_image - spine2",
     "type": "andrewbmchugh-flow-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "interface_oper_state{source=\"spine2\",interface_name=\"e1-1\"}",
       "legendFormat": "oper-state:spine2:ethernet-1/1"
      },
      {
       "expr": "interface_oper_state{source=\"spine2\",interface_name=\"e1-2\"}",
       "legendFormat": "oper-state:spine2:ethernet-1/2"
      },
      {
       "expr": "interface_oper_state{source=\"spine2\",interface_name=\"e1-3\"}",
       "legendFormat": "oper-state:spine2:ethernet-1/3"
      },
      {
       "expr": "interface_oper_state{source=\"spine2\",interface_name=\"e1-4\"}",
       "legendFormat": "oper-state:spine2:ethernet-1/4"
      },
      {
       "expr": "interface_oper_state{source=\"spine2\",interface_name=\"e1-5\"}",
       "legendFormat": "oper-state:spine2:ethernet-1/5"
      },
      {
       "expr": "interface_oper_state{source=\"spine2\",interface_name=\"e1-6\"}",
       "legendFormat": "oper-state:spine2:ethernet-1/6"
      }
     ]
    },
    {
     "title": "router_image - leaf1",
     "type": "andrewbmchugh-flow-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "interface_oper_state{source=\"leaf1\",interface_name=\"e1-1\"}",
       "legendFormat": "oper-state:leaf1:ethernet-1/1"
      },
      {
       "expr": "interface_oper_state{source=\"leaf1\",interface_name=\"e1-2\"}",
       "legendFormat": "oper-state:leaf1:ethernet-1/2"
      },
      {
       "expr": "interface_oper_state{source=\"leaf1\",interface_name=\"e1-3\"}",
       "legendFormat": "oper-state:leaf1:ethernet-1/3"
      },
      {
       "expr": "interface_oper_state{source=\"leaf1\",interface_name=\"e1-4\"}",
       "legendFormat": "oper-state:leaf1:ethernet-1/4"
      },
      {
       "expr": "interface_oper_state{source=\"leaf1\",interface_name=\"e1-5\"}",
       "legendFormat": "oper-state:leaf1:ethernet-1/5"
      }
     ]
    },
    {
     "title": "router_image - leaf2",
     "type": "andrewbmchugh-flow-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "interface_oper_state{source=\"leaf2\",interface_name=\"e1-1\"}",
       "legendFormat": "oper-state:leaf2:ethernet-1/1"
      },
      {
       "expr": "interface_oper_state{source=\"leaf2\",interface_name=\"e1-2\"}",
       "legendFormat": "oper-state:leaf2:ethernet-1/2"
      },
      {
       "expr": "interface_oper_state{source=\"leaf2\",interface_name=\"e1-3\"}",
       "legendFormat": "oper-state:leaf2:ethernet-1/3"
      },
      {
       "expr": "interface_oper_state{source=\"leaf2\",interface_name=\"e1-4\"}",
       "legendFormat": "oper-state:leaf2:ethernet-1/4"
      },
      {
       "expr": "interface_oper_state{source=\"leaf2\",interface_name=\"e1-5\"}",
       "legendFormat": "oper-state:leaf2:ethernet-1/5"
      }
     ]
    },
    {
     "title": "router_image - leaf3",
     "type": "andrewbmchugh-flow-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "interface_oper_state{source=\"leaf3\",interface_name=\"e1-1\"}",
       "legendFormat": "oper-state:leaf3:ethernet-1/1"
      },
      {
       "expr": "interface_oper_state{source=\"leaf3\",interface_name=\"e1-2\"}",
       "legendFormat": "oper-state:leaf3:ethernet-1/2"
      },
      {
       "expr": "interface_oper_state{source=\"leaf3\",interface_name=\"e1-3\"}",
       "legendFormat": "oper-state:leaf3:ethernet-1/3"
      },
      {
       "expr": "interface_oper_state{source=\"leaf3\",interface_name=\"e1-4\"}",
       "legendFormat": "oper-state:leaf3:ethernet-1/4"
      },
      {
       "expr": "interface_oper_state{source=\"leaf3\",interface_name=\"e1-5\"}",
       "legendFormat": "oper-state:leaf3:ethernet-1/5"
      }
     ]
    }
   ]
  }
 ]
}